<?php
require('new_config.php');
require('dbcon.php');
require('functions.php');
require('users.php');
require('product.php');
require('session.php');
require('cart.php');
require('order.php');
require('paginate.php');
require('payment.php');
require_once('cookies.php');
?>